org: elkhoudh
app: labby-prisma
service: yoga-labby

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: index.server
    environment:
      PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
      PRISMA_SECRET: ${env:PRISMA_SECRET}
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: index.playground
    environment:
      PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
      PRISMA_SECRET: ${env:PRISMA_SECRET}
    events:
      - http:
          path: /
          method: get
          cors: true
