org: elkhoudh
app: labby-prisma
service: yoga-labby

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: index.server
    environment:
      PRISMA_ENDPOINT: http://labby-publi-19c6vyqg6ocaw-579895022.us-east-1.elb.amazonaws.com/labby-prisma-server/prod
      PRISMA_SECRET: 5711d4705fbd54cfcc6f3c28ed34f3ef623d1b37386bef7a
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: index.playground
    environment:
      PRISMA_ENDPOINT: http://labby-publi-19c6vyqg6ocaw-579895022.us-east-1.elb.amazonaws.com/labby-prisma-server/prod
      PRISMA_SECRET: 5711d4705fbd54cfcc6f3c28ed34f3ef623d1b37386bef7a
    events:
      - http:
          path: /
          method: get
          cors: true
