org: elkhoudh
app: labby-prisma
service: yoga-labby

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: index.server
    events:
      - http:
          path: /
          method: post
          cors: true
          private: true
  playground:
    handler: index.playground
    events:
      - http:
          path: /
          method: get
          cors: true
          private: true
