AWSTemplateFormatVersion: "2010-09-09"
Description: A very simple VPC for hosting an application

Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:      
      ClusterName: 2019-retreat
      Tags: 
          - Key: Name
            Value: 2019-retreat

  PrismaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: 2019-retreat
      RetentionInDays: 14

  # PrismaTaskDefinition:
  #   Type: "AWS::ECS::TaskDefinition"
  #   Properties:
  #     NetworkMode: awsvpc
  #     RequiresCompatibilities: 
  #       - FARGATE
  #     Family: prisma
  #     Cpu: "1024"
  #     Memory: "2048"
  #     ExecutionRoleArn: "arn:aws:iam::576275871595:role/pma-network-ECSTaskExecutionRole-889RJB8Y8X9P"
  #     TaskRoleArn: "arn:aws:iam::576275871595:role/pma-network-ECSTaskExecutionRole-889RJB8Y8X9P"
  #     Tags: 
  #       - Key: Name
  #         Value: 2019-retreat
  #     ContainerDefinitions:
  #       - Name: "prisma-container"
  #         Image: "prismagraphql/prisma:1.34"
  #         Essential: true
  #         PortMappings:
  #           - ContainerPort: 60000
  #         Ulimits:
  #           - Name: nofile
  #             HardLimit: 1000000
  #             SoftLimit: 1000000
  #         LogConfiguration:
  #           LogDriver: awslogs
  #           Options:
  #             awslogs-group: !Ref PrismaLogGroup
  #             awslogs-region: !Ref AWS::Region
  #             awslogs-stream-prefix: prisma
  #         Environment:
  #           - Name: PRISMA_CONFIG
  #             Value: !Sub |
  #                 port: 60000
  #                 managementApiSecret: '{{resolve:secretsmanager:rds-2019-retreat:SecretString:password}}'
  #                 databases:
  #                   default:
  #                     connector: postgres
  #                     host: "prskudbshk6067.cfxzlxkybce5.us-east-1.rds.amazonaws.com"
  #                     port: 5432
  #                     user: '{{resolve:secretsmanager:rds-2019-retreat:SecretString:username}}'
  #                     password: '{{resolve:secretsmanager:rds-2019-retreat:SecretString:password}}'
  #                     migrations: true
  #           - Name: JAVA_OPTS
  #             Value: -Xmx1350m

  # PrismaService:
  #   Type: "AWS::ECS::Service"
  #   Properties:
  #     ServiceName: Prisma2019Retreat
  #     LaunchType: FARGATE
  #     TaskDefinition: !Ref 'PrismaTaskDefinition'
  #     Cluster: !Ref ECSCluster
  #     DesiredCount: 1
  #     LoadBalancers: 
  #       - ContainerName: prisma-container
  #         ContainerPort: 60000
  #         TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:576275871595:targetgroup/prisma-2019-retreat/ec7df7543512dfdb"
  #     NetworkConfiguration:
  #       AwsvpcConfiguration:
  #         AssignPublicIp: DISABLED
  #         Subnets:
  #           - "subnet-08b9a02bc52f99ef4"
  #           - "subnet-0c97c1db74689492c"
  #         SecurityGroups:
  #           - "sg-0c004047020a47eb5"
  