AWSTemplateFormatVersion: "2010-09-09"
Description: A very simple VPC for hosting an application

Parameters:
  DBName:
    Type: String
    Description: The name of the DB

Resources:
  DBInstanceCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ["", ["rds-password-", !Ref DBName]]
      GenerateSecretString:
        SecretStringTemplate: '{"username": "master"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: !Ref DBName
      DBSubnetGroupDescription: "Subnet group for the API database"
      SubnetIds: 
        - Fn::ImportValue: "PrivateSubnet01"
        - Fn::ImportValue: "PrivateSubnet02"

  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName: !Ref DBName
      PubliclyAccessible: false
      VPCSecurityGroups:
        - "sg-0c6afdcc3c0c2a587"
      DBInstanceClass: "db.t3.small"
      Engine: "postgres"
      AllocatedStorage: "100"
      DBSubnetGroupName: !Ref DBSubnetGroup
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBInstanceCredentials, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBInstanceCredentials, ':SecretString:password}}' ]]
      Tags: 
        - Key: Name
          Value: !Ref DBName
