AWSTemplateFormatVersion: "2010-09-09"
Description: A very simple VPC for hosting an application

Resources:
  RDSInstanceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rds-2019-retreat
      GenerateSecretString:
        SecretStringTemplate: '{"username": "master"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName: "prisma"
      PubliclyAccessible: false
      VPCSecurityGroups:
        - "sg-0c6afdcc3c0c2a587"
      DBInstanceClass: "db.t3.small"
      Engine: "postgres"
      AllocatedStorage: "100"
      DBSubnetGroupName: "pma-network-rdssubnetgroup-14f0hxcf47mla"
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:password}}' ]]
      Tags: 
        - Key: Name
          Value: 2019-retreat

  PrismaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: 2019-retreat
      RetentionInDays: 14

  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '30'
      Subnets:
        - "subnet-0a0a3dbeced01914c"
        - "subnet-0131432180cf2b54e"
      SecurityGroups:
        - "sg-0101c880dc7691be0"
      Tags: 
        - Key: Name
          Value: 2019-retreat
  
  PrismaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "prisma-2019-retreat"
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /status
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: "vpc-05db80beaa9e86a13"
      TargetType: 'ip'
      Tags: 
        - Key: Name
          Value: 2019-retreat

  PublicLoadBalancerListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref 'PublicLoadBalancer'
      Protocol: HTTP
      Port: 80

  PublicLoadBalancerListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: 'arn:aws:acm:us-east-1:576275871595:certificate/44c2ccb9-2333-43f8-8ad6-07a191c8ecfe'
      DefaultActions:
        - TargetGroupArn: !Ref 'PrismaTargetGroup'
          Type: 'forward'
      LoadBalancerArn: !Ref 'PublicLoadBalancer'
      Protocol: HTTPS
      Port: 443

  PrismaTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities: 
        - FARGATE
      Family: prisma
      Cpu: "1024"
      Memory: "2048"
      ExecutionRoleArn: "arn:aws:iam::576275871595:role/pma-network-ECSTaskExecutionRole-889RJB8Y8X9P"
      TaskRoleArn: "arn:aws:iam::576275871595:role/pma-network-ECSTaskExecutionRole-889RJB8Y8X9P"
      Tags: 
        - Key: Name
          Value: 2019-retreat
      ContainerDefinitions:
        - Name: prisma-container
          Image: 'prismagraphql/prisma:1.34'
          Essential: true
          PortMappings:
            - ContainerPort: 60000
          Ulimits:
            - Name: nofile
              HardLimit: 1000000
              SoftLimit: 1000000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref PrismaLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: prisma
          Environment:
            - Name: PRISMA_CONFIG
              Value: !Sub |
                  port: 60000
                  managementApiSecret: '{{resolve:secretsmanager:${RDSInstanceSecret}:SecretString:password}}'
                  databases:
                    default:
                      connector: postgres
                      host: ${RDSInstance.Endpoint.Address}
                      port: ${RDSInstance.Endpoint.Port}
                      user: '{{resolve:secretsmanager:${RDSInstanceSecret}:SecretString:username}}'
                      password: '{{resolve:secretsmanager:${RDSInstanceSecret}:SecretString:password}}'
                      migrations: true
            - Name: JAVA_OPTS
              Value: -Xmx1350m

  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:      
      ClusterName: 2019-retreat
      Tags: 
          - Key: Name
            Value: 2019-retreat


  PrismaService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: Prisma
      LaunchType: FARGATE
      TaskDefinition: !Ref 'PrismaTaskDefinition'
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LoadBalancers: 
        - ContainerName: prisma-container
          ContainerPort: 60000
          TargetGroupArn: !Ref PrismaTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - "subnet-0a0a3dbeced01914c"
            - "subnet-0131432180cf2b54e"
          SecurityGroups:
            - "sg-0c004047020a47eb5"
  