AWSTemplateFormatVersion: "2010-09-09"
Description: A very simple VPC for hosting an application

Resources:
  RDSInstanceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rds-2019-retreat
      GenerateSecretString:
        SecretStringTemplate: '{"username": "master"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName: "prisma"
      PubliclyAccessible: false
      VPCSecurityGroups:
        - "sg-0c6afdcc3c0c2a587"
      DBInstanceClass: "db.t3.small"
      Engine: "postgres"
      AllocatedStorage: "100"
      DBSubnetGroupName: "pma-network-rdssubnetgroup-14f0hxcf47mla"
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:password}}' ]]
      Tags: 
        - Key: Name
          Value: 2019-retreat
